server:
  port: 8080
  
logging:
  level:
    br:
      com:
        vector:
          next: debug
          
compass:
     api:
       project:
          version: 1.0
          
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
    
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  server:
    error: 
       include-binding-errors: always
       include-message: always